#!/usr/bin/env python3
"""
Production RAG Pipeline Example

This script demonstrates how to use the complete RAG pipeline with real LLM integration
for production deployment. It shows the exact flow described in your AI prompt.

Usage:
    python production_example.py

Environment Variables:
    OPENAI_API_KEY - Your OpenAI API key
    AZURE_OPENAI_API_KEY - Your Azure OpenAI API key  
    AZURE_OPENAI_ENDPOINT - Your Azure OpenAI endpoint
    ANTHROPIC_API_KEY - Your Anthropic API key
"""

import os
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

from rag_papers.generation.prompts import QueryProcessor
from rag_papers.generation.generator import RAGGenerator, MockGenerator
from rag_papers.generation.verifier import ResponseVerifier

# Import production LLM generators (if available)
try:
    from rag_papers.generation.production_llm import (
        LLMFactory, create_production_rag_generator, load_llm_config_from_env
    )
    PRODUCTION_AVAILABLE = True
except ImportError:
    PRODUCTION_AVAILABLE = False


def demonstrate_exact_ai_prompt_flow():
    """
    Demonstrate the exact flow from your AI prompt:
    User Query → Prompt Creation → Response Generation → Quality Check → Final Answer
    """
    
    print("=" * 70)
    print("🤖 Production RAG Pipeline - AI Prompt Implementation")
    print("=" * 70)
    
    # Step 1: Initialize components
    print("\\n🔧 Step 1: Initializing Pipeline Components")
    print("   📝 prompts.py - Dynamic prompt creation")
    print("   ⚡ generator.py - LLM integration")  
    print("   🔍 verifier.py - Quality verification")
    
    query_processor = QueryProcessor()
    response_verifier = ResponseVerifier()
    
    # Try to use production LLM, fallback to mock
    if PRODUCTION_AVAILABLE and has_api_keys():
        print("   🚀 Using PRODUCTION LLM integration")
        rag_generator = create_production_rag_generator()
    else:
        print("   🧪 Using MOCK generator (add API keys for production LLMs)")
        rag_generator = RAGGenerator(generator=MockGenerator())
    
    # Sample context (simulates retrieved documents from your RAG system)
    context = """
    Deep learning is a subset of machine learning that uses artificial neural networks 
    with multiple layers (hence "deep") to model and understand complex patterns in data. 
    It's inspired by the structure and function of the human brain, using interconnected 
    nodes (neurons) organized in layers.
    
    Key characteristics of deep learning:
    1. Hierarchical learning: Each layer learns increasingly complex features
    2. Automatic feature extraction: No need for manual feature engineering
    3. Large data requirements: Typically needs massive datasets to train effectively
    4. Computational intensity: Requires significant processing power (GPUs)
    
    Common applications include:
    - Computer vision (image recognition, object detection)
    - Natural language processing (translation, chatbots)
    - Speech recognition and synthesis
    - Autonomous vehicles
    - Medical diagnosis and drug discovery
    """
    
    # Test query from your AI prompt example
    user_query = "What is deep learning?"
    
    print(f"\\n📝 User Query: '{user_query}'")
    print(f"📄 Context: {len(context)} characters of retrieved content")
    
    # Step 2: Prompt Creation (prompts.py)
    print("\\n🧠 Step 2: Prompt Creation (prompts.py)")
    processed_query = query_processor.preprocess_query(user_query)
    
    print(f"   ✅ Intent detected: {processed_query.intent.value}")
    print(f"   ✅ Keywords extracted: {', '.join(processed_query.keywords[:5])}")
    print(f"   ✅ Entities found: {', '.join(processed_query.entities[:3])}")
    print(f"   ✅ Query normalized: '{processed_query.normalized_query}'")
    
    # Step 3: Response Generation (generator.py)
    print("\\n⚡ Step 3: Response Generation (generator.py)")
    print("   📤 Sending prompt to LLM...")
    
    generated_response = rag_generator.generate_answer(
        context=context,
        query=user_query,
        processed_query=processed_query
    )
    
    print(f"   ✅ Response generated by: {generated_response.model_used}")
    print(f"   ✅ Response length: {len(generated_response.text)} characters")
    print(f"   ✅ Model confidence: {generated_response.confidence:.2f}")
    
    # Step 4: Quality Check (verifier.py)
    print("\\n🔍 Step 4: Quality Check (verifier.py)")
    quality_score = response_verifier.verify_response(
        response=generated_response.text,
        query=user_query,
        context=context
    )
    
    print(f"   📊 Overall quality score: {quality_score.overall_score:.3f}")
    print(f"   📊 Relevance score: {quality_score.relevance_score:.3f}")
    print(f"   📊 Coherence score: {quality_score.coherence_score:.3f}")
    print(f"   📊 Completeness score: {quality_score.completeness_score:.3f}")
    print(f"   🔍 Quality issues detected: {len(quality_score.issues)}")
    
    # Quality threshold check
    is_acceptable = response_verifier.is_acceptable(quality_score, threshold=0.7)
    
    if is_acceptable:
        print("   ✅ PASSED: Response meets quality criteria!")
    else:
        print("   ⚠️  FLAGGED: Response needs improvement")
        if quality_score.suggestions:
            print("   💡 Suggestions:")
            for suggestion in quality_score.suggestions[:2]:
                print(f"      • {suggestion}")
    
    # Step 5: Final Answer
    print("\\n🎯 Step 5: Final Answer")
    print("=" * 50)
    print(generated_response.text)
    print("=" * 50)
    
    # Summary
    print("\\n📋 Pipeline Summary:")
    print(f"   • Query processed in: prompts.py (intent: {processed_query.intent.value})")
    print(f"   • Response generated by: generator.py ({generated_response.model_used})")
    print(f"   • Quality verified by: verifier.py (score: {quality_score.overall_score:.3f})")
    print(f"   • Final status: {'✅ Approved' if is_acceptable else '⚠️  Needs review'}")


def demonstrate_multiple_query_types():
    """Demonstrate the pipeline with different query types as mentioned in the AI prompt."""
    
    print("\\n" + "=" * 70)
    print("🎯 Multiple Query Types Demonstration")
    print("=" * 70)
    
    # Initialize components
    query_processor = QueryProcessor()
    
    if PRODUCTION_AVAILABLE and has_api_keys():
        rag_generator = create_production_rag_generator()
    else:
        rag_generator = RAGGenerator(generator=MockGenerator())
    
    response_verifier = ResponseVerifier()
    
    # Test different query types
    test_cases = [
        {
            "query": "What is machine learning?",
            "context": "Machine learning is a method of data analysis that automates analytical model building...",
            "expected_intent": "definition"
        },
        {
            "query": "Explain how neural networks learn",
            "context": "Neural networks learn through a process called backpropagation, adjusting weights based on errors...",
            "expected_intent": "explanation"
        },
        {
            "query": "Compare supervised vs unsupervised learning",
            "context": "Supervised learning uses labeled data while unsupervised learning finds patterns in unlabeled data...",
            "expected_intent": "comparison"
        },
        {
            "query": "How to implement a CNN?",
            "context": "To implement a CNN, start by defining convolutional layers, then pooling layers, followed by dense layers...",
            "expected_intent": "how_to"
        }
    ]
    
    for i, test_case in enumerate(test_cases, 1):
        print(f"\\n{'-' * 40}")
        print(f"Test Case {i}: {test_case['query']}")
        print(f"{'-' * 40}")
        
        # Process query
        processed = query_processor.preprocess_query(test_case['query'])
        print(f"Detected Intent: {processed.intent.value}")
        
        # Generate response
        response = rag_generator.generate_answer(
            context=test_case['context'],
            query=test_case['query'],
            processed_query=processed
        )
        
        # Verify quality
        quality = response_verifier.verify_response(
            response.text, test_case['query'], test_case['context']
        )
        
        print(f"Quality Score: {quality.overall_score:.3f}")
        print(f"Response: {response.text[:100]}...")
        
        # Check if intent matches expectation
        intent_match = processed.intent.value == test_case['expected_intent']
        print(f"Intent Detection: {'✅' if intent_match else '⚠️'} {processed.intent.value}")


def has_api_keys() -> bool:
    """Check if any production API keys are available."""
    return any([
        os.getenv("OPENAI_API_KEY"),
        os.getenv("AZURE_OPENAI_API_KEY"),
        os.getenv("ANTHROPIC_API_KEY")
    ])


def show_configuration_guide():
    """Show how to configure for production use."""
    
    print("\\n" + "=" * 70)
    print("⚙️  Production Configuration Guide")
    print("=" * 70)
    
    print("\\n🔑 API Key Configuration:")
    print("Set environment variables for your preferred LLM provider:")
    print()
    print("For OpenAI:")
    print("   export OPENAI_API_KEY='your-openai-api-key'")
    print()
    print("For Azure OpenAI:")
    print("   export AZURE_OPENAI_API_KEY='your-azure-key'")
    print("   export AZURE_OPENAI_ENDPOINT='https://your-resource.openai.azure.com'")
    print("   export AZURE_OPENAI_DEPLOYMENT='your-deployment-name'")
    print()
    print("For Anthropic:")
    print("   export ANTHROPIC_API_KEY='your-anthropic-key'")
    
    print("\\n🔧 Usage Examples:")
    print('''
# Using OpenAI
from rag_papers.generation.production_llm import LLMFactory
generator = LLMFactory.create_openai_generator(model_name="gpt-4")

# Using Azure OpenAI  
generator = LLMFactory.create_azure_generator(
    deployment_name="gpt-4",
    api_version="2023-12-01-preview"
)

# Using Anthropic
generator = LLMFactory.create_anthropic_generator(model_name="claude-3-sonnet-20240229")
''')


def main():
    """Main demonstration function."""
    
    try:
        # Core demonstration from AI prompt
        demonstrate_exact_ai_prompt_flow()
        
        # Multiple query types
        demonstrate_multiple_query_types()
        
        # Configuration guide
        show_configuration_guide()
        
        print("\\n" + "=" * 70)
        print("🎉 Production RAG Pipeline Demonstration Complete!")
        print("=" * 70)
        
        print("\\n✨ Implementation matches your AI prompt requirements:")
        print("   ✅ prompts.py - Dynamic prompt creation based on query type")
        print("   ✅ generator.py - LLM integration with multiple providers")
        print("   ✅ verifier.py - Heuristic scoring (0-1) for quality assessment")
        print("   ✅ Modular and maintainable architecture")
        print("   ✅ Robust error handling and fallback mechanisms")
        print("   ✅ Support for multiple query types and contexts")
        
        if not has_api_keys():
            print("\\n💡 To use production LLMs, set API keys in environment variables")
            print("   Currently using mock generator for demonstration")
        else:
            print("\\n🚀 Production LLM integration active!")
            
    except Exception as e:
        print(f"\\n❌ Error during demonstration: {e}")
        import traceback
        traceback.print_exc()
        return 1
    
    return 0


if __name__ == "__main__":
    sys.exit(main())